package com.spring.microservices.model;

public enum ButterOrderStatusEnum {
    NEW, VALIDATION_PENDING, VALIDATED, VALIDATION_EXCEPTION, ALLOCATION_PENDING, ALLOCATED, ALLOCATION_ERROR, PENDING_INVENTORY,
    PICKED_UP, DELIVERED, DELIVERY_EXCEPTION, CANCELLED
}
